dosports/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuarios/', include('gestion_usuarios.urls')),
    url(r'^eventos/', include('gestion_eventos.urls')),
    url(r'^rest/', include('rest.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
    url(r'^$', 'gestion_usuarios.views.inicio',name='index'),
    url(r'^inicio$', 'gestion_usuarios.views.inicio_login',name='inicio'),
    url(r'^insertar-deportes', 'datos_iniciales.deportes.deportes_view'),
    url(r'^insertar-loc', 'datos_iniciales.deportes.inser_local'),
)

gestion_usuarios/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('gestion_usuarios.views',
    url(r'^hello$','hello_world',name='hello_world' ),
    url(r'^crear','crear_usuario',name='crear_usuario' ),
    url(r'^mis-eventos','mis_eventos',name='mis_eventos' ),
    url(r'^mis-suscripciones','mis_suscripciones',name='mis_suscripciones' ),
    url(r'^mi-perfil','mi_perfil',name='mi_perfil' ),
)

rest/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('rest.views',
    url(r'^auth','auth_user',name='auth' ),
)

gestion_usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Usuario(User):
    GENEROS = (
        (0,'MASCULINO'),
        (1,'FEMENINO'),
    )
    PUNTOS = (
        (0,'DEFICIENTE'),
        (1,'MAL'),
        (2,'REGULAR'),
        (3,'BIEN'),
        (4,'MUY BIEN'),
        (5,'EXCELENTE'),

    )
    fecha_nacimiento = models.DateField(verbose_name='Fecha de nacimiento',blank=True,null=True)
    genero = models.IntegerField(choices=GENEROS,verbose_name='Genero')
    puntuacion = models.IntegerField(choices=PUNTOS,verbose_name='Puntuación',blank=True,null=True)

    def edad(self):
        today = date.today()
        if self.fecha_nacimiento:
            return today.year - self.fecha_nacimiento.year - ((today.month, today.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))
        return False

gestion_usuarios/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from gestion_usuarios.models import Usuario

class UsuarioForm(ModelForm):

    class Meta:
        model = Usuario
        fields = ('username','first_name','last_name','email','password','fecha_nacimiento','genero',)
        widgets = {
            'password' : forms.PasswordInput(),
            'fecha_nacimiento': forms.DateInput(attrs={'type':'date'}),
        }

gestion_usuarios/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from gestion_usuarios.forms import UsuarioForm
from django.contrib.auth.models import *
from django.contrib.auth.decorators import login_required
from gestion_eventos.models import Evento,ParticipantesEvento,Usuario,Comentarios
# Create your views here.
def hello_world(request):
    return JsonResponse({0:'Hola mundo'})

def inicio(request):
    grupos = Group.objects.all()
    if not grupos:
        usuarios = Group(name='Usuarios')
        usuarios.save()
        usuarios.permissions.add(
            Permission.objects.get(codename='add_evento'),
            Permission.objects.get(codename='add_comentarios'),
            Permission.objects.get(codename='add_participantesevento'),
        )
    return render(request,'index.html',{

    })

@login_required
def inicio_login(request):
    return redirect('listar_eventos')

def crear_usuario(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            u = form.save(commit=False)
            u.set_password(u.password)
            u.save()
            u.groups.add(Group.objects.get(name='Usuarios'))
            return redirect('inicio')
    return render(request,'register.html',{
        'form' : form
    })

@login_required
def mis_eventos(request):
    eventos = Evento.objects.filter(creador=request.user.id)
    return render(request,'listar_mis_eventos.html',{
        'eventos':eventos
    })

@login_required
def mis_suscripciones(request):
    suscripciones = [x.evento for x in ParticipantesEvento.objects.filter(jugadores__id__in=[request.user.id])]
    return render(request,'listar_mis_suscripciones.html',{
        'suscripciones':suscripciones
    })

@login_required
def mi_perfil(request):
    u = Usuario.objects.get(id=request.user.id)
    comentarios = Comentarios.objects.filter(usuario=request.user.id)[:3]
    return render(request,'mi_perfil.html',{
        'usuario': u,
        'comentarios': comentarios
    })

gestion_usuarios/templates/listar_mis_eventos.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block css %}
    <link href="{{ STATIC_URL }}admin/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}admin/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}admin/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
{% endblock %}

{% block contenido %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Basic Data Tables example with responsive plugin</h5>
            </div>
            <div class="ibox-content">

            <table class="table table-striped table-bordered table-hover dataTables-example" >
            <thead>
            <tr>
                <th>Rendering engine</th>
                <th>Browser</th>
                <th>Platform(s)</th>
                <th>Engine version</th>
                <th>CSS grade</th>
            </tr>
            </thead>
            <tbody>

            <tr class="gradeC">
                <td>Misc</td>
                <td>IE Mobile</td>
                <td>Windows Mobile 6</td>
                <td class="center">-</td>
                <td class="center">C</td>
            </tr>
            <tr class="gradeC">
                <td>Misc</td>
                <td>PSP browser</td>
                <td>PSP</td>
                <td class="center">-</td>
                <td class="center">C</td>
            </tr>
            <tr class="gradeU">
                <td>Other browsers</td>
                <td>All others</td>
                <td>-</td>
                <td class="center">-</td>
                <td class="center">U</td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <th>Rendering engine</th>
                <th>Browser</th>
                <th>Platform(s)</th>
                <th>Engine version</th>
                <th>CSS grade</th>
            </tr>
            </tfoot>
            </table>

            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}admin/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{{ STATIC_URL }}admin/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{{ STATIC_URL }}admin/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{{ STATIC_URL }}admin/js/plugins/dataTables/dataTables.tableTools.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.dataTables-example').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
                }
            });
        });
    </script>
{% endblock %}

gestion_usuarios/templates/listar_mis_suscripciones.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block css %}

{% endblock %}

{% block contenido %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Mis eventos</h5>
            </div>
            <div class="ibox-content">

            <table class="table table-striped table-bordered table-hover dataTables-example" >
            <thead>
            <tr>
                <th>Nombre</th>
                <th>Fecha</th>
                <th>Deporte</th>
                <th>Lugar</th>
                <th>Opciones</th>
            </tr>
            </thead>
            <tbody>
            {% for e in suscripciones %}
            <tr class="gradeC">
                <td>{{ e.nombre }}</td>
                <td>{{ e.fecha }}</td>
                <td>{{ e.deporte }}</td>
                <td>{{ e.lugar }}</td>
                <td>
                    <a href="{% url 'ver_evento' e.id %}"><i class="fa fa-trophy"></i> Ver mas</a>
                </td>
            </tr>
            {% endfor %}

            </tbody>

            </table>
            {% if not suscripciones %}
                <p>No hay datos</p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

gestion_usuarios/templates/mi_perfil.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block contenido %}
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="ibox-content p-xl">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>{{ user.get_full_name }}</h1>
                            <img src="{{ STATIC_URL }}admin/img/a4.jpg">
                        </div>

                        <div class="col-sm-6 text-right">

                            <h4 class="text-navy">{% if usuario.puntuacion %}{{ usuario.puntuacion }}{% else %} Sin puntuar {% endif %}</h4>
                            <span>{% if usuario.edad %}{{ usuario.edad }} años{% else %} No hay fecha de nacimiento registrada {% endif %}</span>
                            <address>
                                <strong>{{ usuario.get_genero_display }}</strong><br>
                                {{ usuario.email }} <br>
                            </address>
                            <p>
                                <span><strong>Nombre de usuario:</strong> {{ usuario.username }}</span><br/>
                                <span><strong>Fecha de registro:</strong> {{ usuario.date_joined }}</span>
                            </p>
                        </div>
                    </div>

                    <div class="table-responsive m-t">
                        <table class="table invoice-table">
                            <thead>
                            <tr>
                                <th>Ultimos comentarios</th>
                                <th>Fecha</th>
                                <th>Enlace</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for c in comentarios %}
                            <tr>
                                <td><div><strong>{{ c.evento.nombre }}</strong></div>
                                    <small>{{ c.descripcion }}</small></td>
                                <td>{{ c.fecha }}</td>
                                <td><a href="{% url 'ver_evento' c.evento.id %}"><i class="fa fa-calendar"></i> Ver evento</td></a>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% if not comentarios %}
                        <p align="center"> No has hecho comentarios</p>
                    {% endif %}
                    </div><!-- /table-responsive -->


                    <!--div class="well m-t"><strong>Comments</strong>
                        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
                    </div-->
                </div>
        </div>
    </div>
{% endblock %}