dosports/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuarios/', include('gestion_usuarios.urls')),
    url(r'^eventos/', include('gestion_eventos.urls')),
    url(r'^rest/', include('rest.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
    url(r'^$', 'gestion_usuarios.views.inicio',name='index'),
    url(r'^inicio$', 'gestion_usuarios.views.inicio_login',name='inicio'),
    url(r'^insertar-deportes', 'datos_iniciales.deportes.deportes_view'),
    url(r'^insertar-loc', 'datos_iniciales.deportes.inser_local'),
)

gestion_eventos/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('gestion_eventos.views',
    url(r'^crear$','crear_evento',name='crear_evento' ),
    url(r'^listar$','listar_eventos',name='listar_eventos' ),
    url(r'^ver/(\d+)$','ver_evento',name='ver_evento' ),
    url(r'^suscribirse/(\d+)$','suscribirse_evento',name='suscribirse_evento'),
    url(r'^anular-sus/(\d+)$','anular_suscripcion',name='anular_suscripcion'),
    url(r'^comentar/(\d+)$','comentar',name='comentar'),
    url(r'^calendario$','calendario',name='calendario'),

)

rest/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin


urlpatterns = patterns('rest.views',
    url(r'^auth','auth_user',name='auth' ),
)

gestion_eventos/models.py
from django.db import models
from gestion_usuarios.models import Usuario
from django.utils import timezone

# Create your models here.
class Deporte(models.Model):
    nombre = models.CharField(max_length=150,verbose_name='Deporte')

    def __str__(self):
        return self.nombre

class Lugar(models.Model):
    TIPOS = (
        (0,'PRIVADO'),
        (1,'PUBLICO'),
    )
    nombre = models.CharField(max_length=150,verbose_name='Nombre')
    tipo = models.IntegerField(choices=TIPOS,verbose_name='Tipos',default=1)
    latitud = models.FloatField()
    longitud = models.FloatField()
    web = models.URLField(blank=True,null=True)

    def __str__(self):
        return self.nombre

class Evento(models.Model):
    DIFICULTADES = (
        (0,'INDIFERENTE'),
        (1,'PRINCIPIANTE'),
        (2,'INTERMEDIO'),
        (3,'AVANZADO')
    )
    nombre = models.CharField(max_length=150,verbose_name='Nombre del evento')
    creador = models.ForeignKey(Usuario)
    fecha = models.DateTimeField(verbose_name='Fecha del evento')
    plazas = models.IntegerField()
    dificultad = models.IntegerField(choices=DIFICULTADES,verbose_name='Nivel')
    deporte = models.ForeignKey(Deporte)
    lugar = models.ForeignKey(Lugar)

    def estado(self):
        print(self.fecha)
        print(timezone.datetime.now())
        if self.plazas_disponibles() == 0 or self.fecha < timezone.now():
            return False
        return True

    def plazas_disponibles(self):
        total_participantes = ParticipantesEvento.objects.get(evento=self).jugadores.all().count()
        return self.plazas - total_participantes

    def porcentaje(self):
        total_participantes = ParticipantesEvento.objects.get(evento=self).jugadores.all().count()
        return int((100*total_participantes)/self.plazas)

class Comentarios(models.Model):
    usuario = models.ForeignKey(Usuario)
    fecha = models.DateTimeField(auto_now=True)
    descripcion = models.TextField()
    evento = models.ForeignKey(Evento)

class ParticipantesEvento(models.Model):
    evento = models.ForeignKey(Evento)
    jugadores = models.ManyToManyField(Usuario)

gestion_eventos/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from gestion_eventos.models import Evento
from bootstrap3_datetime.widgets import DateTimePicker

class EventoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(EventoForm, self).__init__(*args, **kwargs)
        #self.fields['fecha'].widget.attrs.update({'class': 'datetimepicker'})
        self.fields['fecha'].widget.attrs.update({'readonly': True})

    class Meta:
        model = Evento
        exclude = ('creador',)
        widgets = {
            'fecha': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm","pickSeconds": False}),

        }

gestion_eventos/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from gestion_eventos.forms import EventoForm
from gestion_usuarios.models import Usuario
from gestion_eventos.models import Evento,ParticipantesEvento,Comentarios
# Create your views here.
@login_required
def crear_evento(request):
    form = EventoForm()
    if request.method == 'POST':
        form = EventoForm(request.POST)
        if form.is_valid():
            e = form.save(commit=False)
            e.creador = Usuario.objects.get(id=request.user.id)
            e.save()
            ParticipantesEvento(evento=e).save()
            return redirect('ver_evento',e.id)

    return render(request,'crear_evento.html',{
        'form': form
    })

@login_required
def listar_eventos(request):
    eventos = Evento.objects.all().order_by('-fecha')
    return render(request,'listar_eventos.html',{
        'eventos': eventos,
        'total' : eventos.count()
    })

@login_required
def ver_evento(request,id):
    try:
        evento = Evento.objects.get(id=id)
    except Exception:
        redirect('inicio')

    ids = [x.id for x in ParticipantesEvento.objects.get(evento=evento).jugadores.all()]
    suscrito=False
    if request.user.id in ids or request.user.id == evento.creador.id:
        suscrito = True

    comentarios  = Comentarios.objects.filter(evento=evento)

    return render(request,'ver_evento.html',{
        'evento': evento,
        'suscrito': suscrito,
        'comentarios' : comentarios
    })

@login_required
def suscribirse_evento(request,id_ev):
    usuario = Usuario.objects.get(id=request.user.id)
    ParticipantesEvento.objects.get(evento=id_ev).jugadores.add(usuario)
    return redirect('listar_eventos')

@login_required
def anular_suscripcion(request,id_ev):
    usuario = Usuario.objects.get(id=request.user.id)
    ParticipantesEvento.objects.get(evento=id_ev).jugadores.remove(usuario)
    return redirect('listar_eventos')

@login_required
def comentar(request,id_ev):
    evento = Evento.objects.get(id=id_ev)
    Comentarios(
        usuario=Usuario.objects.get(id=request.user.id),
        evento=evento,
        descripcion=request.POST['message']
    ).save()
    return redirect('ver_evento',id_ev)

@login_required
def calendario(request):
    eventos = Evento.objects.all()
    array = []
    for e in eventos:
        dic = {}
        dic['id'] = e.id
        dic['title'] = e.nombre
        f = e.fecha.replace(tzinfo=None)
        dic['start'] = str(f)
        dic['allDay'] = 'false'
        dic['url'] = '/eventos/ver/'+str(e.id)
        array.append(dic)
    return render(request,'calendar.html',{
        'eventos' : array
    })

gestion_eventos/templates/calendar.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block css %}
    <link href="{{ STATIC_URL }}admin/css/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}admin/css/plugins/fullcalendar/fullcalendar.print.css" rel='stylesheet' media='print'>
{% endblock %}

{% block contenido %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Calendario de eventos </h5>
            </div>
            <div class="ibox-content">
                <div id="calendar"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}admin/js/plugins/fullcalendar/moment.min.js"></script>
    <script src="{{ STATIC_URL }}admin/js/plugins/fullcalendar/fullcalendar.min.js"></script>
    <script>
        $(document).ready(function(){
            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                events : {{ eventos|safe }},
            });
        });
    </script>
{% endblock %}

gestion_eventos/templates/crear_evento.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block css %}
    {{ form.media }}
{% endblock %}
{% block contenido %}
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Creación de eventos <small>Crear un evento deportivo.</small></h5>
            </div>
            <div class="ibox-content">
                <form method="post" action="" class="form-horizontal">{% csrf_token %}


                    <div class="col-lg-12">
                        <div class="col-lg-5">
                            {% bootstrap_field form.nombre layout="verical" %}
                        </div>
                        <div class="col-lg-1"></div>
                        <div class="col-lg-5">
                            {% bootstrap_field form.plazas layout="verical"%}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-5">
                            {% bootstrap_field form.dificultad layout="verical"%}
                        </div>
                        <div class="col-lg-1"></div>
                        <div class="col-lg-5">
                            {% bootstrap_field form.deporte layout="verical" %}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-5">
                            {% bootstrap_field form.lugar %}
                        </div>
                        <div class="col-lg-1"></div>
                        <div class="col-lg-5">
                            {% bootstrap_field form.fecha layout="vertical" %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-md">Crear</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

gestion_eventos/templates/listar_eventos.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block contenido %}
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInRight">

            <div class="ibox-content m-b-sm border-bottom">
                <div class="p-xs">
                    <div class="pull-left m-r-md">
                        <i class="fa fa-globe text-navy mid-icon"></i>
                    </div>
                    <h2>Actualmente hay {{ total }} eventos disponibles...</h2>
                </div>
                <div class="search-form">
                    <form action="index.html" method="get">
                        <div class="input-group">
                            <input type="text" placeholder="Busca eventos..." name="search" class="form-control input-lg">
                            <div class="input-group-btn">
                                <button class="btn btn-lg btn-primary" type="submit">
                                    Search
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>



            <div class="ibox-content forum-container">

                <div class="forum-title">

                </div>
                {% for e in eventos %}
                    <div class="forum-item active">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="forum-icon">
                                    <i class="fa fa-futbol-o"></i>
                                </div>
                                <a href="{% url 'ver_evento' e.id %}" class="forum-item-title">{{ e.nombre }}</a>
                                <div class="forum-sub-title">Creador: {{ e.creador.get_full_name }}</div>
                            </div>

                            <div class="col-md-1 forum-info">
                                <span class="views-number">
                                    {{ e.plazas_disponibles }}
                                </span>
                                <div>
                                    <small>Plazas disponibles</small>
                                </div>
                            </div>
                            <div class="col-md-2 forum-info">
                                <span>
                                    {{ e.fecha }}
                                </span>
                                <div>
                                    <small>Fecha</small>
                                </div>
                            </div>
                            <div class="col-md-2 forum-info">
                                <a href="{% url 'ver_evento' e.id %}" class="btn btn-sm btn-primary">
                                    Ver mas
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

gestion_eventos/templates/ver_evento.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block css %}

    <!--script src="http://maps.googleapis.com/maps/api/js"></script-->
{% endblock %}
{% block contenido %}
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">
            <div class="ibox">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="m-b-md">
                                {% if evento.porcentaje < 100 and not suscrito%}
                                    <a href="{% url 'suscribirse_evento' evento.id %}" class="btn btn-primary btn-md pull-right">Suscribirse</a>
                                {% elif evento.porcentaje == 100 %}
                                    <span class="pull-right"><strong>No hay plazas disponibles</strong></span>
                                {% elif user.id != evento.creador.id %}
                                    <span class="pull-right"><strong>Ya estas suscrito!</strong></span><br>
                                    <a href="{% url 'anular_suscripcion' evento.id %}" class="btn btn-warning btn-md pull-right">Anular suscripcion</a>
                                {% else %}
                                    <span class="pull-right"><strong>Eres el creador del evento!</strong></span><br>
                                {% endif %}
                                <h2>{{ evento.nombre }}</h2>
                            </div>
                            <dl class="dl-horizontal">
                                <dt>Estado:</dt> <dd><span class="label label-{% if evento.estado %}primary">Abierto{% else %}danger">Cerrado{% endif %}</span></dd>
                            </dl>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-5">
                            <dl class="dl-horizontal">

                                <dt>Creado por:</dt> <dd>{{ evento.creador.get_full_name }}</dd>
                                <dt>Plazas disponibles:</dt> <dd>  {{ evento.plazas_disponibles }}</dd>
                                <dt>Lugar:</dt> <dd>{{ evento.lugar }}</dd>
                                <dt>Nivel:</dt> <dd> 	{{ evento.get_dificultad_display }} </dd>
                            </dl>
                        </div>
                        <div class="col-lg-7" id="cluster_info">
                            <dl class="dl-horizontal" >

                                <dt>Fecha:</dt> <dd>{{ evento.fecha }}</dd>
                                <dt>Participantes:</dt>
                                <dd class="project-people">
                                <a href=""><img alt="image" class="img-circle" src="{{STATIC_URL}}admin/img/a3.jpg"></a>
                                <a href=""><img alt="image" class="img-circle" src="{{STATIC_URL}}admin/img/a1.jpg"></a>
                                <a href=""><img alt="image" class="img-circle" src="{{STATIC_URL}}admin/img/a2.jpg"></a>
                                <a href=""><img alt="image" class="img-circle" src="{{STATIC_URL}}admin/img/a4.jpg"></a>
                                <a href=""><img alt="image" class="img-circle" src="{{STATIC_URL}}admin/img/a5.jpg"></a>
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <dl class="dl-horizontal">
                                <dt>Completado:</dt>
                                <dd>
                                    <div class="progress progress-striped active m-b-sm">
                                        <div style="width: {{ evento.porcentaje }}%;" class="progress-bar"></div>
                                    </div>
                                    <small>Evento completado en un <strong>{{ evento.porcentaje }}%</strong>.</small>
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <dl class="dl-horizontal">
                                <dt>Compartir: </dt>
                                <div class="col-lg-8">
                                    <i class="fa fa-facebook-square fa-2x"></i>
                                    <i class="fa fa-twitter fa-2x"></i>
                                    <i class="fa fa-google-plus fa-2x"></i>
                                </div>
                            </dl>
                        </div>
                    </div>
                    <div class="row m-t-sm">
                        <div class="col-lg-12">
                        <div class="panel blank-panel">
                        <div class="panel-heading">
                            <div class="panel-options">
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#tab-1" data-toggle="tab">Comentarios</a></li>
                                    <li><a href="#tab-2" data-toggle="tab">Mapas</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="panel-body">

                        <div class="tab-content">
                        <div class="tab-pane active" id="tab-1">
                            <div class="ibox-content">

                        <div class="row">

                            <div class="col-md-12 ">
                                <div class="chat-discussion">
                                    {% for c in comentarios %}
                                    <div class="chat-message">
                                        <img class="message-avatar" src="{{STATIC_URL}}admin/img/a1.jpg" alt="" >
                                        <div class="message">
                                            <a class="message-author" href="#"> {{ c.usuario.get_full_name }} </a>
											<span class="message-date"> {{ c.fecha }} </span>
                                            <span class="message-content">
											{{ c.descripcion }}
                                            </span>
                                        </div>
                                    </div>
                                    {% empty %}
                                    <p>No hay comentarios</p>
                                    {% endfor %}
                                </div>

                            </div>

                        </div>
                        <form action="{% url 'comentar' evento.id %}" method="post">{% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="chat-message-form">
                                        <div class="form-group">
                                            <textarea class="form-control message-input" name="message" placeholder="Ingrese comentario aqui..."></textarea>
                                        </div>

                                    </div>
                                </div>
                            </div><br>
                            <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-success btn-md pull-right">Enviar</button>
                                </div>

                            </div>
                        </form>


                    </div>

                        </div>


                        <div class="tab-pane" id="tab-2">
                            <div class="ibox-content">
                                <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script>
                                <div class="google-map" id="map1"></div>

                            </div>
                        </div>

                        </div>

                        </div>

                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!--script src="http://maps.googleapis.com/maps/api/js"></script-->
    <script type="text/javascript">
        // When the window has finished loading google map


        function init() {


            //var myLatLng = {lat: -25.363, lng: 131.044};
            var la = parseInt({{ evento.lugar.latitud }});
            var lo = parseInt({{ evento.lugar.longitud }});
            var myLatLng = {lat: 39.488127, lng: -6.411293};

            var map = new google.maps.Map(document.getElementById('map1'), {
              zoom: 11,
              center: myLatLng
            });

            var marker = new google.maps.Marker({
              position: myLatLng,
              map: map
              //title: 'Hello World!'
            });

        }
        $(document).init(function(){
            google.maps.event.addDomListener(window, 'load', init);
        });


    </script>
{% endblock %}